### ISSUE TITLE
[Question] simalar projects

### ISSUE THREAD

**Issue by citizenserious** [Magisk-Modules-Alt-Repo/abootloop#1]
Hi [nedorazrab0](https://github.com/nedorazrab0),

thank you for this module.
I am sorry for opening an issue but I do not know where else to ask this

Until now I was using [systemui-bootloop](https://github.com/tsukimio/systemui-bootloop), but it has not got an update for years and seems abandoned.

Are these projects somehow related?
How does these projects differ?

Thanks a lot for clarifying things for me.

**Comment by nedorazrab0** [comment]
> Hi [nedorazrab0](https://github.com/nedorazrab0),
> 
> thank you for this module.
> I am sorry for opening an issue but I do not know where else to ask this
> 
> Until now I was using [systemui-bootloop](https://github.com/tsukimio/systemui-bootloop), but it has not got an update for years and seems abandoned.
> 
> Are these projects somehow related?
> How does these projects differ?
> 
> Thanks a lot for clarifying things for me.
> 

systemui-bootloop disables modules when systemui crashes, abootloop disables modules if you press the power key at boot. These are different projects

**Comment by citizenserious** [comment]
Thank you (:
