### ISSUE TITLE
Bootloader Unlocked Warning

### ISSUE THREAD

**Issue by sekedus** [Magisk-Modules-Alt-Repo/abootloop#2]
Can you change button from just **power** button to:
- **power + volume up**
- or **power + volume down**.

Because **bootloader unlocked warning** always appear when booting.

So I can press power button to **skip bootloader unlocked warning** at boot and magisk module remains active.

![bootloader-unlocked-warning](https://github.com/Magisk-Modules-Alt-Repo/abootloop/assets/25115799/6778f2ce-3827-41fd-880f-f98ff6301cf2)

**Comment by nedorazrab0** [comment]
does this trigger the module?

**Comment by sekedus** [comment]
Yes, all modules are disabled.

**Comment by nedorazrab0** [comment]
I will update the module soon
