### ISSUE TITLE
Install without volume button

### ISSUE THREAD

**Issue by NeverSm1le** [Magisk-Modules-Alt-Repo/abootloop#4]
Is there a way to manually edit the button without go through the setup? My device only have the power button, therefore the setup cannot be completed

**Comment by nedorazrab0** [comment]
install [v1.2](https://github.com/Magisk-Modules-Alt-Repo/abootloop/releases/tag/v1.2) version

**Comment by NeverSm1le** [comment]
> install [v1.2](https://github.com/Magisk-Modules-Alt-Repo/abootloop/releases/tag/v1.2) version

Thank you sir it work!
